<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\CalendarioWidget;
use Filament\Pages\Page;
use Illuminate\Contracts\Support\Htmlable;

class Calendario extends Page
{
//    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.calendario';

    protected static ?string $navigationGroup = 'Agenda';

    // can view only 'admin' users

    public static function canAccess(): bool
    {
        // false if is 'Cliente'
        return !auth()->user()->hasRole('Cliente');
    }

    public function getTitle(): string|Htmlable
    {
        //return parent::getTitle(); // TODO: Change the autogenerated stub
        return '';
    }

    protected function getHeaderWidgets(): array
    {
        return [
            CalendarioWidget::class,
        ];
    }
}
