<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\CalendarioWidget;
use App\Traits\HasEventoForm;
use Filament\Pages\Page;
use Illuminate\Contracts\Support\Htmlable;
use Filament\Actions\Action;

class Calendario extends Page
{
    use HasEventoForm;

//    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.calendario';

    protected static ?string $navigationGroup = 'Agenda';

    public $defaultAction = 'onboarding';

    public $selectedDate = null;
    public $selectedTime = null;

    public function onboardingAction(): Action
    {
        // Usarlo per indicare se la Connessione a Google Calendar è attiva
        return Action::make('onboarding')->modalHeading('Welcome')->visible(fn () => false);
    }
    public static function canAccess(): bool
    {
        // false if is 'Cliente'
        return !auth()->user()->hasRole('Cliente');
    }

    public function getTitle(): string|Htmlable
    {
        //return parent::getTitle(); // TODO: Change the autogenerated stub
        return '';
    }

    protected function getHeaderWidgets(): array
    {
        return [
            CalendarioWidget::class,
        ];
    }


}
